"use client";

import { useEffect, useState } from "react";

type Agent = { unique_id: string; name: string; role: string; avatar?: string; risk_level: string; specialization: string; status: string; survival_state: string };
type Point = { date: string; value: number };
type Position = { symbol: string; quantity: number; average_price: number; current_value: number; unrealized_pnl: number };

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function Home() {
  const [agent, setAgent] = useState<Agent | null>(null);
  const [points, setPoints] = useState<Point[]>([]);
  const [agents, setAgents] = useState<Agent[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  useEffect(() => { Promise.all([fetch(`${api}/api/agents`).then(r => r.json()), fetch(`${api}/api/market/history`).then(r => r.json()), fetch(`${api}/api/portfolio/positions`).then(r => r.json())]).then(([agentList, history, paperPositions]) => { setAgents(agentList); setAgent(agentList[0]); setPoints(history.points); setPositions(paperPositions); }).catch(() => undefined); }, []);
  const latest = points.at(-1)?.value ?? 109.4;
  const first = points[0]?.value ?? 100;
  const path = points.map((point, i) => `${(i / Math.max(points.length - 1, 1)) * 100},${100 - ((point.value - first) / (latest - first || 1)) * 76 - 12}`).join(" ");
  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>AETERNUM</span></div><p className="eyebrow">ECOSYSTEM</p><nav><a className="active" href="#overview">Overview</a><a href="#agents">Agents</a><a href="#market">Market intelligence</a><a href="#risk">Risk & survival</a></nav><div className="mode"><span className="pulse" /> PAPER MODE<br /><small>No live execution</small></div></aside>
    <section className="content"><header><div><p className="eyebrow">COMMAND DECK / 22 AUG 2026</p><h1>Good evening, <em>operator.</em></h1><p className="muted">Aeternum is watching the signal field.</p></div><button className="avatar" aria-label="Open profile">BR</button></header>
      <div className="hero-grid"><section className="hero-card" id="overview"><div className="card-top"><div><p className="eyebrow">TOTAL PORTFOLIO VALUE</p><div className="value">R$ 128,420<span>.76</span></div><div className="positive">↗ +2.84% <small>vs. last month</small></div></div><div className="status-chip"><span className="pulse" /> HEALTHY</div></div><div className="chart"><div className="chart-label">PORTFOLIO PERFORMANCE <span>14D</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Portfolio performance over fourteen days"><polyline points={path} fill="none" stroke="url(#line)" strokeWidth="1.6" vectorEffect="non-scaling-stroke" /><defs><linearGradient id="line"><stop stopColor="#a7f36b"/><stop offset="1" stopColor="#5eead4"/></linearGradient></defs></svg><div className="chart-axis"><span>09 AUG</span><span>16 AUG</span><span>22 AUG</span></div></div></section><section className="aurion-card" id="agents"><div className="orb"><div className="orb-core">✦</div><i /><i /><i /></div><p className="eyebrow">FOUNDING AGENT</p><h2>{agent?.name ?? "Aurion"}</h2><p className="muted">{agent?.specialization ?? "Market intelligence & quantitative research"}</p><div className="agent-meta"><span>GEN 0</span><span className="positive">● ONLINE</span></div><button className="outline">Enter agent view <span>→</span></button></section></div>
      <div className="metric-row"><Metric label="TODAY P&L" value="+R$ 1,284.20" positive /><Metric label="AVAILABLE CASH" value="R$ 24,600.00" /><Metric label="CURRENT DRAWDOWN" value="−3.18%" warning /><Metric label="ACTIVE AGENTS" value="01 / 08" /></div>
      <div className="lower-grid"><section className="panel" id="market"><div className="panel-title"><div><p className="eyebrow">LIVE INTELLIGENCE</p><h3>Signal field</h3></div><button className="icon-button" aria-label="More options">•••</button></div><div className="signal"><span className="signal-icon">↗</span><div><strong>Market regime detected</strong><p className="muted">Constructive momentum across technology. Confidence 68%.</p></div><span className="tag">BULL</span></div><div className="signal"><span className="signal-icon amber">◌</span><div><strong>Volatility compressing</strong><p className="muted">AURION is monitoring a potential breakout window.</p></div><span className="tag amber">WATCH</span></div></section><section className="panel" id="risk"><div className="panel-title"><div><p className="eyebrow">SURVIVAL ENGINE</p><h3>Risk posture</h3></div><span className="risk-score">24 <small>/ 100</small></span></div><div className="risk-bar"><span /></div><div className="risk-foot"><span>LOW EXPOSURE</span><span>CAPITAL PRESERVED</span></div><p className="quote">“The first duty of an intelligence is to remain operational.”</p></section></div>
    </section><aside className="command"><div className="command-head"><span className="online-dot" /> COMMAND CENTER <button aria-label="Close command center">×</button></div><div className="conversation"><div className="message system"><span className="mini-orb">✦</span><div><b>AETERNUM</b><p>All systems nominal. What would you like to explore?</p></div></div><div className="message user">Show me what Aurion is analyzing right now.</div><div className="message system"><span className="mini-orb">✦</span><div><b>AURION</b><p>I’m tracking a constructive shift in technology momentum. No action recommended yet — the signal needs confirmation above resistance.</p><div className="decision"><span>HOLD</span><span>68% CONFIDENCE</span></div></div></div></div><div className="composer"><input aria-label="Command Center message" placeholder="Ask Aeternum anything..." /><button aria-label="Send message">↑</button><small>Enter to send · Paper mode</small></div></aside>
      <section className="ecosystem panel" id="ecosystem"><div className="panel-title"><div><p className="eyebrow">AGENT ECOSYSTEM / NEURAL COMMAND CENTER</p><h3>Living constellation</h3></div><span className="tag">{agents.length || 8} NODES</span></div><div className="agent-tree">{agents.map(item => <div className="agent-node" key={item.unique_id}><span className="node-avatar">{item.unique_id === "AURION" ? "✦" : item.avatar ?? "◈"}</span><div><strong>{item.name.toUpperCase()}</strong><small>{item.role} · {item.status}</small></div><span className="node-risk">{item.risk_level}</span></div>)}</div><p className="demo-note">PAPER SYSTEM · Relationships are local demo state until orchestration persistence is enabled.</p></section>
      <section className="portfolio panel"><div className="panel-title"><div><p className="eyebrow">PAPER PORTFOLIO</p><h3>Simulated positions</h3></div><span className="status-chip">NO LIVE ORDERS</span></div><div className="position-list">{positions.map(position => <div className="position" key={position.symbol}><div><strong>{position.symbol}</strong><small>{position.quantity} units · avg. R$ {position.average_price.toFixed(2)}</small></div><div className="position-price"><strong>R$ {position.current_value.toFixed(2)}</strong><small className="positive">+R$ {position.unrealized_pnl.toFixed(2)}</small></div></div>)}</div></section>
  </main>;
}

function Metric({ label, value, positive, warning }: { label: string; value: string; positive?: boolean; warning?: boolean }) { return <div className="metric"><p className="eyebrow">{label}</p><strong className={positive ? "positive" : warning ? "warning" : ""}>{value}</strong></div>; }
