"use client";
import { useEffect, useState } from "react";
type Agent={unique_id:string;name:string;role:string;avatar?:string;specialization:string;status:string};
type History={data_status:string;points:{date:string;value:number}[]};
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
export default function Home(){
 const [agents,setAgents]=useState<Agent[]>([]); const [history,setHistory]=useState<History>(); const [now,setNow]=useState(new Date());
 useEffect(()=>{const clock=window.setInterval(()=>setNow(new Date()),1000);Promise.all([fetch(`${api}/api/agents`).then(r=>r.json()),fetch(`${api}/api/market/history`).then(r=>r.json())]).then(([a,h])=>{setAgents(a);setHistory(h)});return()=>window.clearInterval(clock)},[]);
 const day=new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric",timeZone:"America/Sao_Paulo"}).format(now); const time=new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:"America/Sao_Paulo"}).format(now);
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span>AETERNUM</div><p className="eyebrow">CENTRO DE COMANDO</p><nav><a className="active" href="#painel">Painel</a><a href="#agentes">Ecossistema de IAs</a><a href="#fontes">Fontes de dados</a><a href="#conexoes">Conexões financeiras</a></nav><div className="mode"><span className="pulse"/> MODO PAPER<br/><small>Nenhuma operação real</small></div></aside><section className="content"><header><div><p className="eyebrow">PAINEL PRINCIPAL</p><h1>Olá, <em>operador.</em></h1><p className="muted">{day}<br/><strong className="clock">{time}</strong> · Horário de Brasília</p></div><div className="aurion-seal" aria-label="Aurion, agente fundador"><div>✦</div><small>AURION<br/>FUNDADOR</small></div></header><div className="hero-grid" id="painel"><Card title="PATRIMÔNIO TOTAL" text="Dados indisponíveis." detail="Nenhuma conexão financeira autorizada."/><Card title="DADOS DE MERCADO" text={history?.points.length?"Dados disponíveis":"Fonte não conectada."} detail={history?.data_status??"Nenhum dado será exibido até uma origem verificável estar disponível."}/></div><section className="panel" id="agentes"><div className="panel-title"><div><p className="eyebrow">ECOSSISTEMA AETERNUM</p><h3>Constelação de inteligências</h3></div><span className="tag">{agents.length} AGENTE{agents.length===1?"":"S"}</span></div><div className="agent-tree">{agents.map(a=><article className="agent-node hologram" key={a.unique_id}><div className="holo-avatar"><span>{a.avatar??"✦"}</span></div><div><strong>{a.name.toUpperCase()}</strong><small>{a.role} · {a.status}</small><small>{a.specialization}</small><small>Geração 0 · Agente fundador</small></div></article>)}</div><p className="empty-note">Novos agentes só surgirão após proposta, revisão e autorização explícita.</p></section><div className="lower-grid"><section className="panel" id="fontes"><p className="eyebrow">PROVENIÊNCIA</p><h3>Fontes de dados</h3><Empty text="Fonte não conectada."/></section><section className="panel" id="conexoes"><p className="eyebrow">OPEN FINANCE</p><h3>Conexões financeiras</h3><Empty text="Nenhuma instituição conectada."/></section></div></section><aside className="command"><div className="command-head"><span className="online-dot"/> AETERNUM <span className="tag">PAPER</span></div><div className="conversation"><div className="message system"><span className="mini-orb">✦</span><div><b>AURION</b><p>Sou o único agente inicial deste ecossistema.</p><p className="muted">Ainda não há dados verificáveis suficientes para concluir.</p></div></div></div></aside></main>;
}
function Card({title,text,detail}:{title:string;text:string;detail:string}){return <section className="hero-card"><p className="eyebrow">{title}</p><div className="empty-value">{text}</div><p className="muted">{detail}</p><button className="outline">Ver fonte <span>→</span></button></section>}
function Empty({text}:{text:string}){return <div className="empty"><strong>{text}</strong><p>Dados indisponíveis.<br/>Nenhuma informação verificável foi encontrada.</p></div>}
